import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { twMerge } from "tailwind-merge";
import { cookies } from "next/headers";
import GlobalProviders from "@/components/GlobalProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ownerToken = cookies().get("accessToken");

  return (
    <html lang="en">
      <GlobalProviders recoveredToken={ownerToken?.value} >
        <body className={twMerge("bg-[#EFEFEF]", inter.className)}>{children}</body>
      </GlobalProviders>
    </html>
  );
}
