import { Metadata } from "next";
import Header from "@/components/Header";
import OnlineUsersSidebar from "@/components/OnlineUsersSidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function InLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <>
            <Header />
            {children}
            <OnlineUsersSidebar />
        </>
    )

}