import { Metadata } from "next";
import ClientSideInLayout from "@/components/ClientSideInLayout";
import { cookies } from "next/headers";
import { serverFetch } from "@/lib/actions";
import { UserInterface } from "@/interfaces/User";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default async function InLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const currentUser = await serverFetch<UserInterface.SimpleType>("/u-s/users/{tokenUserId}");

    return (
        <ClientSideInLayout {...{ currentUser }} >
            {children}
        </ClientSideInLayout>
    )
}