import { Metadata } from 'next';
import ClientSideInLayout from '@/components/ClientSideInLayout';
import { serverFetch } from '@/lib/actions';
import { UserInterface } from '@/interfaces/User';
import Providers from '@/components/Providers';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
export default async function InLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const currentUser = await serverFetch<UserInterface.SimpleType>(
        '/u-s/users/{tokenUserId}'
    );

    if (!currentUser) throw new Error('user not found');

    return (
        <Providers>
            <ClientSideInLayout {...{ currentUser }}>
                {children}
            </ClientSideInLayout>
        </Providers>
    );
}
